### ISSUE TITLE
too many steps to submit a plugin

### ISSUE THREAD

**Issue by justinmk** [neurosnap/neovimcraft#429]
https://neovimcraft.com/ is a nice resource! It's fast, simple, and attractive. But there's really too much friction to submit a new plugin:

1. clone this repo
2. fork this repo...
3. run a make script
4. input lots if things to the script
5. input _tags_, one of which is "plugin" (that should be a default?), which seems pretty important
6. create a PR
7. resolve merge conflicts?

## Suggestion 1

1. in the make script, if a github URL (or other known URL) is provided, skip all steps except the "tags" step.
2. include "plugin" in "tags" if no conflicting tag (such as "config", I guess?) is provided.

## Suggestion 2

1. let users submit new plugins as github issues simply by mentioning a URL
    - user may include optional `tags: foo bar baz` text in the issue
3. a human maintainer labels valid issues as `plugin`
4. a CI job crawls `plugin` issues, gets the URL from the issue text, and updates the json

## Future: crawl github repos?

Does neovimcraft already have a CI job setup to crawl github in any way? 

In https://github.com/neovim/packspec/issues/41 I'm exploring the idea of a very simple plugin "package" format. If it sees uptake, it will be possible to automatically discover plugins by:

1. ask github API for all `pkg.json` files across all repos (is this costly?)
5. any such `pkg.json` file which has `engines: [ "nvim", ... ]` is a Neovim plugin.

**Comment by neurosnap** [comment]
Hi thanks for the kind words!

> let users submit new plugins as github issues simply by mentioning a URL

People are welcome to submit GH issues to add new plugins, but my response time to actually adding them will be low on my priority list.  I also don't have a ton of bandwidth to work on new features in this project atm.  However, since we scrape `awesome-neovim`, users are also welcome to submit plugins there and it'll eventually -- within a few hours -- show up on neovimcraft.  Maybe adding a tagline about that in the README would be helpful.

> include "plugin" in "tags" if no conflicting tag (such as "config", I guess?) is provided.

The reason why we include "plugin" as a tag is because some of these listings are not strictly plugins.  It's weird and awkward, I agree.  I'd honestly just as soon remove the tag entirely.

> Does neovimcraft already have a CI job setup to crawl github in any way?

Yes.  We primarily scrape https://github.com/rockerBOO/awesome-neovim for plugins and use the github API to search for popular neovim plugins.

**Comment by justinmk** [comment]
Ok, https://github.com/neurosnap/neovimcraft/commit/708b59b474c3b516e0ff467c84f840df47b1817d is helpful, thanks.

**Comment by justinmk** [comment]
> We primarily scrape https://github.com/rockerBOO/awesome-neovim for plugins and use the github API to search for popular neovim plugins.

Nice. I listed some searches in https://github.com/neovim/neovim/issues/24221#issuecomment-1616009906 , that is more sustainable than manual curation.

There's also https://github.com/codicocodes/dotfyle
